DROP TABLE BOARD;
DROP SEQUENCE SEQ_BOARD;

CREATE SEQUENCE SEQ_BOARD NOCACHE NOCYCLE;
CREATE TABLE BOARD(
    NO          NUMBER              PRIMARY KEY
    , TITLE     VARCHAR2(1000)      NOT NULL
    , CONTENT   VARCHAR2(4000)      NOT NULL
    , WRITER_NO NUMBER              NOT NULL
);


DROP TABLE MEMBER;
DROP SEQUENCE SEQ_MEMBER;

CREATE SEQUENCE SEQ_MEMBER NOCACHE NOCYCLE;
CREATE TABLE MEMBER(
    NO              NUMBER          PRIMARY KEY
    , ID            VARCHAR2(100)   NOT NULL UNIQUE
    , PWD           VARCHAR2(100)   NOT NULL
    , NICK          VARCHAR2(100)   NOT NULL UNIQUE
    , DEL_YN        CHAR(1)         DEFAULT 'N' CHECK(DEL_YN IN ('Y','N'))
    , ENROLL_DATE   TIMESTAMP       DEFAULT SYSDATE
);

ALTER TABLE BOARD 
ADD CONSTRAINT FK_BOARD_MEMBER 
FOREIGN KEY (WRITER_NO)
REFERENCES MEMBER(NO);


DROP SEQUENCE SEQ_NOTICE;
DROP TABLE NOTICE CASCADE CONSTRAINTS;

CREATE SEQUENCE SEQ_NOTICE NOCACHE NOCYCLE;
CREATE TABLE NOTICE(
    NO          NUMBER              PRIMARY KEY
    , TITLE     VARCHAR2(1000)      NOT NULL
    , CONTENT   VARCHAR2(4000)      NOT NULL
    , WRITER_NO NUMBER              NOT NULL
    , HIT       NUMBER              DEFAULT 1
);




DROP TABLE ADMIN;
DROP SEQUENCE SEQ_ADMIN;

CREATE SEQUENCE SEQ_ADMIN NOCACHE NOCYCLE;
CREATE TABLE ADMIN(
    NO              NUMBER          PRIMARY KEY
    , ID            VARCHAR2(100)   NOT NULL UNIQUE
    , PWD           VARCHAR2(100)   NOT NULL
    , NICK          VARCHAR2(100)   NOT NULL UNIQUE
);

INSERT INTO ADMIN(NO, ID, PWD, NICK) VALUES(SEQ_ADMIN.NEXTVAL , 'ADMIN01' , '1234' , '°ü¸®ÀÚ01');
COMMIT;





